#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Thu Nov 30 16:24:55 +0000 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L axi_vip_v1_1_13 -L processing_system7_vip_v1_0_15 -L smartconnect_v1_0 -L xilinx_vip -prj tb_bram_combine_custom_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_13 -L processing_system7_vip_v1_0_15 -L smartconnect_v1_0 -L xilinx_vip -prj tb_bram_combine_custom_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
