#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 30 14:41:20 +0000 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_bram_combine_custom_func_synth -key {Post-Synthesis:sim_1:Functional:tb_bram_combine_custom} -tclbatch tb_bram_combine_custom.tcl -protoinst "protoinst_files/CS411_task1.protoinst" -protoinst "protoinst_files/bd_b08f.protoinst" -log simulate.log"
xsim tb_bram_combine_custom_func_synth -key {Post-Synthesis:sim_1:Functional:tb_bram_combine_custom} -tclbatch tb_bram_combine_custom.tcl -protoinst "protoinst_files/CS411_task1.protoinst" -protoinst "protoinst_files/bd_b08f.protoinst" -log simulate.log

