# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fpga/fpga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga || ORIG_REF_NAME==fpga} -quiet] -quiet

# IP: bd/fpga/ip/fpga_processing_system7_0_0/fpga_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_processing_system7_0_0 || ORIG_REF_NAME==fpga_processing_system7_0_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_proc_sys_reset_0_0/fpga_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_proc_sys_reset_0_0 || ORIG_REF_NAME==fpga_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_smartconnect_0_0/fpga_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_smartconnect_0_0 || ORIG_REF_NAME==fpga_smartconnect_0_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_0_0/fpga_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_0_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_1_0/fpga_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_1_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_2_0/fpga_axi_bram_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_2_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_3_0/fpga_axi_bram_ctrl_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_3_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_3_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_0_bram_0/fpga_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_1_bram_0/fpga_axi_bram_ctrl_1_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_2_bram_0/fpga_axi_bram_ctrl_2_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_2_bram_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_2_bram_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_axi_bram_ctrl_3_bram_0/fpga_axi_bram_ctrl_3_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_axi_bram_ctrl_3_bram_0 || ORIG_REF_NAME==fpga_axi_bram_ctrl_3_bram_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_xlconstant_0_0/fpga_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_xlconstant_0_0 || ORIG_REF_NAME==fpga_xlconstant_0_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_mat_mul_system_0_0/fpga_mat_mul_system_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mat_mul_system_0_0 || ORIG_REF_NAME==fpga_mat_mul_system_0_0} -quiet] -quiet

# XDC: /home/user/vivado_step4_team4/vivado_step4_team4.gen/sources_1/bd/fpga/fpga_ooc.xdc
