# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/vivado_step4_team4/vivado_step4_team4.srcs/sources_1/bd/fpga/ip/fpga_axi_bram_ctrl_1_0/fpga_axi_bram_ctrl_1_0.xci
# IP: The module: 'fpga_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/vivado_step4_team4/vivado_step4_team4.gen/sources_1/bd/fpga/ip/fpga_axi_bram_ctrl_1_0/fpga_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/vivado_step4_team4/vivado_step4_team4.srcs/sources_1/bd/fpga/ip/fpga_axi_bram_ctrl_1_0/fpga_axi_bram_ctrl_1_0.xci
# IP: The module: 'fpga_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/vivado_step4_team4/vivado_step4_team4.gen/sources_1/bd/fpga/ip/fpga_axi_bram_ctrl_1_0/fpga_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
